***************
*** 9,20 ****
  
  O_TARGET := kernel.o
  
- export-objs = signal.o sys.o kmod.o context.o ksyms.o pm.o exec_domain.o printk.o
  
  obj-y     = sched.o dma.o fork.o exec_domain.o panic.o printk.o \
  	    module.o exit.o itimer.o info.o time.o softirq.o resource.o \
  	    sysctl.o acct.o capability.o ptrace.o timer.o user.o \
- 	    signal.o sys.o kmod.o context.o
  
  obj-$(CONFIG_UID16) += uid16.o
  obj-$(CONFIG_MODULES) += ksyms.o
--- 9,20 ----
  
  O_TARGET := kernel.o
  
+ export-objs = signal.o sys.o kmod.o context.o ksyms.o pm.o exec_domain.o printk.o rcupdate.o
  
  obj-y     = sched.o dma.o fork.o exec_domain.o panic.o printk.o \
  	    module.o exit.o itimer.o info.o time.o softirq.o resource.o \
  	    sysctl.o acct.o capability.o ptrace.o timer.o user.o \
+ 	    signal.o sys.o kmod.o context.o rcupdate.o
  
  obj-$(CONFIG_UID16) += uid16.o
  obj-$(CONFIG_MODULES) += ksyms.o
