#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "mipsel-uclibc-gcc -DL_ENDIAN -DTERMIO -Os -fomit-frame-pointer -Wall"
  #define PLATFORM "linux-mipsel"
  #define DATE "Tue Apr 22 08:32:04 CEST 2008"
#endif
