***************
*** 9,15 ****
  
  O_TARGET := netfilter.o
  
- export-objs = ip_conntrack_standalone.o ip_conntrack_ftp.o ip_fw_compat.o ip_nat_standalone.o ip_tables.o
  
  # Multipart objects.
  list-multi		:= ip_conntrack.o iptable_nat.o ipfwadm.o ipchains.o
--- 9,15 ----
  
  O_TARGET := netfilter.o
  
+ export-objs = ip_conntrack_standalone.o ip_conntrack_ftp.o ip_fw_compat.o ip_nat_standalone.o ip_tables.o arp_tables.o
  
  # Multipart objects.
  list-multi		:= ip_conntrack.o iptable_nat.o ipfwadm.o ipchains.o
***************
*** 31,45 ****
  # connection tracking
  obj-$(CONFIG_IP_NF_CONNTRACK) += ip_conntrack.o
  
- # IRC support
- obj-$(CONFIG_IP_NF_IRC) += ip_conntrack_irc.o
- obj-$(CONFIG_IP_NF_NAT_IRC) += ip_nat_irc.o
- 
  # connection tracking helpers
  obj-$(CONFIG_IP_NF_FTP) += ip_conntrack_ftp.o
  
  # NAT helpers 
  obj-$(CONFIG_IP_NF_NAT_FTP) += ip_nat_ftp.o
  
  # generic IP tables 
  obj-$(CONFIG_IP_NF_IPTABLES) += ip_tables.o
--- 31,43 ----
  # connection tracking
  obj-$(CONFIG_IP_NF_CONNTRACK) += ip_conntrack.o
  
  # connection tracking helpers
  obj-$(CONFIG_IP_NF_FTP) += ip_conntrack_ftp.o
+ obj-$(CONFIG_IP_NF_IRC) += ip_conntrack_irc.o
  
  # NAT helpers 
  obj-$(CONFIG_IP_NF_NAT_FTP) += ip_nat_ftp.o
+ obj-$(CONFIG_IP_NF_NAT_IRC) += ip_nat_irc.o
  
  # generic IP tables 
  obj-$(CONFIG_IP_NF_IPTABLES) += ip_tables.o
***************
*** 76,81 ****
  obj-$(CONFIG_IP_NF_TARGET_LOG) += ipt_LOG.o
  obj-$(CONFIG_IP_NF_TARGET_ULOG) += ipt_ULOG.o
  obj-$(CONFIG_IP_NF_TARGET_TCPMSS) += ipt_TCPMSS.o
  
  # backwards compatibility 
  obj-$(CONFIG_IP_NF_COMPAT_IPCHAINS) += ipchains.o
--- 74,85 ----
  obj-$(CONFIG_IP_NF_TARGET_LOG) += ipt_LOG.o
  obj-$(CONFIG_IP_NF_TARGET_ULOG) += ipt_ULOG.o
  obj-$(CONFIG_IP_NF_TARGET_TCPMSS) += ipt_TCPMSS.o
+ 
+ # generic ARP tables
+ obj-$(CONFIG_IP_NF_ARPTABLES) += arp_tables.o
+ 
+ # just filtering instance of ARP tables for now
+ obj-$(CONFIG_IP_NF_ARPFILTER) += arptable_filter.o
  
  # backwards compatibility 
  obj-$(CONFIG_IP_NF_COMPAT_IPCHAINS) += ipchains.o
