cp -f ./include/linux/netfilter_ipv4/ip_conntrack.h.sav ./include/linux/netfilter_ipv4/ip_conntrack.h
cp -f ./Makefile.sav ./Makefile
cp -f ./drivers/char/avalanche_vlynq/Makefile.sav ./drivers/char/avalanche_vlynq/Makefile
cp -f ./drivers/char/avalanche_vlynq/avalanche_vlynq.o.sav ./drivers/char/avalanche_vlynq/avalanche_vlynq.o
cp -f ./drivers/char/avalanche_keypad/Makefile.sav ./drivers/char/avalanche_keypad/Makefile
cp -f ./drivers/char/avalanche_lcd/Makefile.sav ./drivers/char/avalanche_lcd/Makefile
cp -f ./drivers/char/avalanche_led/avalanche_led.o.sav ./drivers/char/avalanche_led/avalanche_led.o
cp -f ./drivers/char/avalanche_led/Makefile.sav ./drivers/char/avalanche_led/Makefile
cp -f ./drivers/net/avalanche_vmac/Makefile.sav ./drivers/net/avalanche_vmac/Makefile
cp -f ./drivers/net/avalanche_wlan/Makefile.sav ./drivers/net/avalanche_wlan/Makefile
cp -f ./drivers/net/avalanche_cpmac/Makefile.sav ./drivers/net/avalanche_cpmac/Makefile
cp -f ./drivers/net/avalanche_cpmac/avalanche_cpmac.o.sav ./drivers/net/avalanche_cpmac/avalanche_cpmac.o
cp -f ./drivers/net/avalanche_usb/Makefile.sav ./drivers/net/avalanche_usb/Makefile
cp -f ./drivers/net/avalanche_usb_slave20/Makefile.sav ./drivers/net/avalanche_usb_slave20/Makefile
cp -f ./drivers/ticfg/Makefile.sav ./drivers/ticfg/Makefile
cp -f ./drivers/ticfg/ticfg.o.sav ./drivers/ticfg/ticfg.o
cp -f ./drivers/adam2/Makefile.sav ./drivers/adam2/Makefile
cp -f ./drivers/adam2/adam2.o.sav ./drivers/adam2/adam2.o
cp -f ./drivers/atm/sangam_atm_B_5.00.04/ar0700mp.bin.sav ./drivers/atm/sangam_atm_B_5.00.04/ar0700mp.bin
cp -f ./drivers/atm/sangam_atm_B_5.00.04/Makefile.sav ./drivers/atm/sangam_atm_B_5.00.04/Makefile
cp -f ./drivers/atm/sangam_atm_B_5.00.04/ar0700db.bin.sav ./drivers/atm/sangam_atm_B_5.00.04/ar0700db.bin
cp -f ./drivers/i2c/avalanche_i2c/Makefile.sav ./drivers/i2c/avalanche_i2c/Makefile
cp -f ./net/bridge/wb_device.o.sav ./net/bridge/wb_device.o
cp -f ./net/bridge/wb_config.o.sav ./net/bridge/wb_config.o
cp -f ./net/bridge/Makefile.sav ./net/bridge/Makefile
cp -f ./net/bridge/wb_main.o.sav ./net/bridge/wb_main.o
cp -f ./net/ipv4/Makefile.sav ./net/ipv4/Makefile
cp -f ./net/ipv4/ipfastpath.o.sav ./net/ipv4/ipfastpath.o
cp -f ./net/ipv4/netfilter/ip_nat_ipsec.o.sav ./net/ipv4/netfilter/ip_nat_ipsec.o
cp -f ./net/ipv4/netfilter/Makefile.sav ./net/ipv4/netfilter/Makefile
cp -f ./net/ipv4/netfilter/ip_conntrack_ipsec.o.sav ./net/ipv4/netfilter/ip_conntrack_ipsec.o
cp -f ./arch/mips/mips-boards/ti_avalanche/Makefile.sav ./arch/mips/mips-boards/ti_avalanche/Makefile
cp -f ./arch/mips/mips-boards/ti_avalanche/ti_generic/ti_generic.o.sav ./arch/mips/mips-boards/ti_avalanche/ti_generic/ti_generic.o
cp -f ./arch/mips/mips-boards/ti_avalanche/ti_generic/Makefile.sav ./arch/mips/mips-boards/ti_avalanche/ti_generic/Makefile
cp -f ./arch/mips/mips-boards/ti_avalanche/ti_adam2/ti_adam2.o.sav ./arch/mips/mips-boards/ti_avalanche/ti_adam2/ti_adam2.o
cp -f ./arch/mips/mips-boards/ti_avalanche/ti_adam2/Makefile.sav ./arch/mips/mips-boards/ti_avalanche/ti_adam2/Makefile
cp -f ./arch/mips/mips-boards/ti_avalanche/ti_sangam/ti_sangam.o.sav ./arch/mips/mips-boards/ti_avalanche/ti_sangam/ti_sangam.o
cp -f ./arch/mips/mips-boards/ti_avalanche/ti_sangam/Makefile.sav ./arch/mips/mips-boards/ti_avalanche/ti_sangam/Makefile
cp -f ./arch/mips/mips-boards/ti_avalanche/inflater/Makefile.sav ./arch/mips/mips-boards/ti_avalanche/inflater/Makefile
cp -f ./arch/mips/mips-boards/ti_avalanche/inflater/Decoder.o.sav ./arch/mips/mips-boards/ti_avalanche/inflater/Decoder.o
cp -f ./arch/mips/mips-boards/ti_avalanche/inflater/inflate.o.sav ./arch/mips/mips-boards/ti_avalanche/inflater/inflate.o
cp -f ./srec2bin.sav ./srec2bin
